server {
    server_name warkop1001cc.cloud www.warkop1001cc.cloud;

    client_max_body_size 10M;
    root /var/www/frontend;
    index index.html;

    # Static Menu Photos diserve langsung Nginx
    location /uploads/ {
        alias /var/www/backend/public/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Socket.IO Reverse Proxy
    location /socket.io/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # API Reverse Proxy ke Express
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Single Page Application (Routing /menu, /kasir, dll)
    location / {
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/warkop1001cc.cloud/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/warkop1001cc.cloud/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.warkop1001cc.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = warkop1001cc.cloud) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name warkop1001cc.cloud www.warkop1001cc.cloud;
    return 404; # managed by Certbot
}
